# Workflow name
name: Hello

on:
  push:
    branches:
      - main

    paths: 
      -'**.html'

# Jobs
jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Say hello to user
        run: echo "Hello $USER"
