name: portfolio

on:
  push:
    branches: [main]


permissions:
  pages:write
  id-token:write

jobs:
  deploy: 
    runs on : ununtu_latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.url }}

    steps:
        # get access to portfolio code
      - name: Checkout Code
        uses: actions/Checkout@v4

        # Setup github pages
      - name: Setup Githup pages
        uses: actions/configure-Githup-pages@v4

        # staticd code artifacts
      - name: Upload static files
        uses: actions/upload-pages-artifacts@v4



